<a href="https://colab.research.google.com/github/Rahul-chandran02/python-data-analysis/blob/main/numpy_practiced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Numpy
!pip install numpy

In [4]:
import numpy as np
#Creating an array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#SHaping the array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [7]:
arr = np.arange(0,20,2).reshape(10,1)
print(arr)
print(f" the Dimention is {arr.ndim}")

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]]
 the Dimention is 2


In [8]:
#Creating an matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#Identity Matrix
np.eye(4,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
#Operations using Numpy
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

print("Addition: ", arr1+arr2)
print("Substraction: ", arr1-arr2)
print("Multiplication: ", arr1*arr2)
print("Division: ", arr1/arr2)

Addition:  [6 6 6 6 6]
Substraction:  [-4 -2  0  2  4]
Multiplication:  [5 8 9 8 5]
Division:  [0.2 0.5 1.  2.  5. ]


In [11]:
#Uiversal Functions
arr = np.array([2,4,6,8,10])

#Square
print(np.sqrt(arr))

#Expo
print(np.exp(arr))

#log
print(np.log(arr))

#Sin
print(np.sin(arr))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]


In [14]:
#Array Slicing and indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [27]:
print(arr[0][0])
arr[1:]

1


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [32]:
arr[0:2,-1:]

array([[ 5],
       [10]])

In [34]:
arr[0,2] = 100
print(arr)

[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [38]:
d = np.array([1,2,3,4,5,6])

#Mean
mean = np.mean(d)
print("The mean is ", mean)

#Median
median = np.median(d)
print("The median is ", median)

#Standard deviation
std = np.std(d)
print("Standard diviation is ", std)

#Variance
var = np.var(d)
print("Variance is ", var)

The mean is  3.5
The median is  3.5
Standard diviation is  1.707825127659933
Variance is  2.9166666666666665


In [43]:
#Logical Operations
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

arr[(arr>=5) & (arr<=12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])