<a href="https://colab.research.google.com/github/Rahul-chandran02/python-data-analysis/blob/main/Python_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy
!pip install numpy

In [ ]:
import numpy as np
#Creating an array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#SHaping the array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
arr = np.arange(0,20,2).reshape(10,1)
print(arr)
print(f" the Dimention is {arr.ndim}")

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]]
 the Dimention is 2


In [ ]:
#Creating an matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Identity Matrix
np.eye(4,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
#Operations using Numpy
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

print("Addition: ", arr1+arr2)
print("Substraction: ", arr1-arr2)
print("Multiplication: ", arr1*arr2)
print("Division: ", arr1/arr2)

Addition:  [6 6 6 6 6]
Substraction:  [-4 -2  0  2  4]
Multiplication:  [5 8 9 8 5]
Division:  [0.2 0.5 1.  2.  5. ]


In [ ]:
#Uiversal Functions
arr = np.array([2,4,6,8,10])

#Square
print(np.sqrt(arr))

#Expo
print(np.exp(arr))

#log
print(np.log(arr))

#Sin
print(np.sin(arr))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
